[profile.default]
retries = { backoff = "exponential", count = 2, delay = "1s" }

[profile.ci]
fail-fast = false
failure-output = "immediate-final"
success-output = "never"
status-level = "skip"

[profile.ci.junit]
path = "junit.xml"
report-name = "trashpanda-tests"
