name: Release Please
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  id-token: write
  issues: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: rust
      # The logic below handles the crates.io publication
      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v5
      - name: Setup Rust
        if: ${{ steps.release.outputs.release_created }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: cargo build --release
      - name: Run tests
        if: ${{ steps.release.outputs.release_created }}
        run: cargo test --all-features
      - name: Publish to crates.io
        if: ${{ steps.release.outputs.release_created }}
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
