name: Release Please
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
  id-token: write
  issues: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: rust

      # The logic below handles the crates.io publication
      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4
      - name: Setup Rust
        if: ${{ steps.release.outputs.release_created }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Install just
        if: ${{ steps.release.outputs.release_created }}
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Install tools
        if: ${{ steps.release.outputs.release_created }}
        uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - name: Publish to crates.io
        if: ${{ steps.release.outputs.release_created }}
        run: just publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
